### ISSUE TITLE
Auto reload on adding new item

### ISSUE THREAD

**Issue by anuraagbaishya** [anuraagbaishya/Auxilium#9]
The listings need to be auto updated when a new item is added

**Comment by uttapong** [comment]
I see it's already redirected to the corresponded service page. Would you like me to take this up without reloading?

**Comment by anuraagbaishya** [comment]
What do you want to solve if you want to take up a reload issue without reloading?

**Comment by anuraagbaishya** [comment]
This issue has been fixed already. Sorry
